name: Bug report
description: Create a report to help us resolve an issue
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      placeholder: "Steps to reproduce the behavior:\n\n1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: 'Add screenshots to help explain your problem.'
    validations:
      required: true
  - type: textarea
    id: device_information
    attributes:
      label: Device information
      placeholder: "- Device: [e.g. iPhone6]\n- OS: [e.g. iOS8.1]\n- Browser [e.g. stock browser, safari]\n- Version [e.g. 22]"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: BetterTTV Version
      placeholder: '7.x.x'
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      placeholder: 'Add any other context about the problem here.'
  - type: checkboxes
    id: upgrade_check
    attributes:
      label: Version Check
      options:
        - label: I have checked that I'm using the newest version of BetterTTV available.
          required: true
